/**
 * PawGuard API layer — public barrel.
 *
 * Everything a feature module needs lives behind `@/lib/api`:
 *
 * ```ts
 * import { apiGet, apiGetPage, ApiError } from "@/lib/api";
 * import { getErrorMessage, QUERY_KEYS } from "@/lib/api";
 * import { useApiQuery } from "@/lib/api";
 * ```
 *
 * Feature services live in `@/services/api/<module>` and build on this layer.
 */

export { env, apiConfig, type ApiConfig } from "./config";
export {
  API_DEFAULT_RETRY,
  API_HEADERS,
  API_ROUTES,
  API_STALE_TIME_MS,
  API_TIMEOUT_MS,
  API_UPLOAD_TIMEOUT_MS,
  AUTH_TOKEN_STORAGE_KEYS,
  QUERY_KEYS,
} from "./constants";
export {
  ApiError,
  getErrorMessage,
  getFieldErrors,
  isApiError,
  isRetryableError,
  normalizeError,
  type ApiErrorKind,
} from "./errors";
export type {
  AdoptionApplicationCreate,
  AdoptionApplicationResponse,
  AdoptionStatus,
  AlertSeverity,
  ApiErrorDetail,
  ApiResponse,
  AppointmentCancelRequest,
  AppointmentQueryParams,
  AppointmentStatus,
  AuthTokens,
  AuthUser,
  BlogPostResponse,
  CampaignStatus,
  CampaignType,
  CompanionPetCreate,
  CompanionPetsQueryParams,
  CompanionPetResponse,
  ContactLocationResponse,
  ContactMessageCreate,
  ContentStatus,
  DeviceContext,
  DeviceType,
  DogProfileResponse,
  DogQueryParams,
  DogStatus,
  PublicDogScanResponse,
  SafetyTagResponse,
  SafetyTagScanRequest,
  SafetyTagScanResponse,
  PetAppointmentCreate,
  PetAppointmentResponse,
  PetReminderCreate,
  PetReminderResponse,
  PetSightingCreate,
  PetSightingResponse,
  ReminderKind,
  VetClinicQueryParams,
  VetClinicResponse,
  DonationCampaignResponse,
  DonationCreate,
  DonationOrderResponse,
  DonationQueryParams,
  DonationResponse,
  DonationStatus,
  DonationStatusUpdate,
  DonationType,
  DonationVerifyRequest,
  DonorProfileCreate,
  DonorProfileResponse,
  DonorProfileUpdate,
  DownloadUrlResponse,
  EmailVerificationConfirmRequest,
  FAQEntryResponse,
  FieldValidationError,
  FosterPlacementResponse,
  FosterPlacementStatus,
  FosterProfileCreate,
  FosterProfileResponse,
  FosterProgressLogCreate,
  FosterProgressLogResponse,
  FosterStatus,
  FosterSupplyDispatchResponse,
  SupplyRequestCreate,
  FoundReportCreate,
  FoundReportResponse,
  GrievanceCreate,
  GrievanceResponse,
  GrievanceStatus,
  LegalDocumentResponse,
  LegalDocumentType,
  LoginRequest,
  LoginResponse,
  LoginResult,
  LostFoundPhotoUploadRequest,
  LostFoundPhotoUploadResponse,
  LostFoundQueryParams,
  LostFoundReportStatus,
  LostReportCreate,
  LostReportResponse,
  MatchStatus,
  MFAEnrollConfirmRequest,
  MFAEnrollResponse,
  MFARequiredResponse,
  MFAVerifyRequest,
  NotificationPreferenceResponse,
  NotificationPreferenceUpdate,
  NotificationResponse,
  OAuthAccountInfo,
  OAuthLinkRequest,
  OAuthLoginRequest,
  OwnershipClaimSubmit,
  Page,
  PaginatedResponse,
  PaginationMeta,
  PaginationParams,
  PasswordResetConfirmRequest,
  PasswordResetRequest,
  PublicContentResponse,
  PublicHeroStats,
  PublicRescueStatusResponse,
  QueryParams,
  RefreshRequest,
  RefreshResponse,
  ReportMatchResponse,
  RequestOptions,
  RescueDispatchResponse,
  RescuePhysicalCondition,
  RescueQueryParams,
  RescueReportResponse,
  RescueRequestCreate,
  RescueRequestResponse,
  RescueSeverity,
  RescueStatus,
  SessionInfo,
  ShiftAttendanceResponse,
  SortParams,
  Species,
  SponsorshipCreate,
  SponsorshipResponse,
  SponsorshipStatus,
  SponsorshipStatusUpdate,
  SuccessResponse,
  SuccessStoryResponse,
  ServiceFeedbackCreate,
  ServiceFeedbackResponse,
  SupplyItemType,
  TransparencyStats,
  UnreadCountResponse,
  UrgentAlertResponse,
  UserDashboardSummary,
  UserProfile,
  UserProfileUpdate,
  VeterinaryPartnerResponse,
  VolunteerProfileCreate,
  VolunteerProfileResponse,
  VolunteerServiceSummary,
  VolunteerShiftResponse,
  VolunteerStatus,
  VolunteerApplicationInfo,
  VolunteerLifecycleStatus,
  VolunteerMeStatusResponse,
} from "./types";
export {
  buildQueryString,
  buildUrl,
  getApiUrl,
} from "./url";
export {
  clampPage,
  getEmptyPaginationMeta,
  getPageCount,
  getPageOffset,
  getPageRange,
  getPaginationParams,
} from "./pagination";
export {
  formatApiDate,
  parseApiDate,
  toApiDate,
  toApiDateTime,
} from "./date";
export {
  apiDelete,
  apiGet,
  apiGetPage,
  apiPatch,
  apiPost,
  apiPut,
  httpClient,
  type ApiRequestConfig,
} from "./client";
export * as auth from "./auth";
export * from "./hooks";
